{{ config(materialized='table') }}

SELECT
    id as job_ad_id,
    headline,
    description_text,
    employer_name,
    workplace_city,
    workplace_region,
    workplace_country,
    occupation_field_concept_id,
    occupation_field_label,
    occupation_concept_id,
    occupation_label,
    employment_type,
    duration,
    salary_type,
    scope_of_work_min,
    scope_of_work_max,
    publication_date,
    last_publication_date,
    application_deadline,
    vacancies,
    relevance,
    experience_required,
    driving_license_required,
    access_to_own_car,
    application_url,
    extracted_at,
    occupation_field_code,
    occupation_field_name,
    source_type,
    removed
FROM {{ ref('src_jobtech__job_ads') }}